- test/cogctl_test.exs
This PR fixes the cogctl chat-handler creation test by using the null chat adapter.
**Tests for this will continue to fail until https://github.com/operable/cog/pull/454 is merged.**
Fixes https://github.com/operable/cog/issues/456
> Use the null chat adapter

- lib/cogctl/actions/users.ex
- lib/cogctl/actions/users/create.ex
- test/cogctl_test.exs
The first and last names in the User model should be optional fields. If the fields are empty, when they are displayed we should return empty strings. 
Fixes https://github.com/operable/cog/issues/362
> Issue #362: Make first and last names optional

- lib/cogctl/actions/permissions.ex
- lib/cogctl/actions/roles/info.ex
- lib/cogctl/optparse.ex
- mix.exs
- mix.lock
- test/cogctl_test.exs
This PR
* adds the role_show api allowing for the addition of permissions info in a new permission format 
```
%{permissions: [%{namespace: "namespace1",
id: "some id",
name: "some permission"},
%{namespace: "namespace2",
id: "some other id",
name:"some other permission"}]
}
```
* adds permissions to the role model
**Tests will fail until Cog PR # is merged to master.**
Fixes https://github.com/operable/cog/issues/382
> Add roles info and update permissions with new format

- lib/cogctl/actions/users/info.ex
- test/cogctl_test.exs
Pulls group membership information for a user and display each group name and id.
**Tests will fail until PR https://github.com/operable/cog/pull/475 is merged to master.**
Fixes https://github.com/operable/cog/issues/474
> Add groups to users

- lib/cogctl/actions/groups.ex
- mix.exs
- mix.lock
- test/cogctl_test.exs
This PR displays roles for the groups command. The Name and Id of the granted roles will be displayed.
**Tests will fail until PR #https://github.com/operable/cog/pull/480 is merged to master.**
Fixes https://github.com/operable/cog/issues/462
> add roles, users, and groups to groups#show and #index

- lib/cogctl/actions/bundles/enable.ex
When enabling a bundle the enabled flag should be set to true.
> Set bundle the enabled flag to true

- mix.exs
- mix.lock
- test/cogctl_test.exs
Use the master cogAPI and correct the error message in the relay deletion.
> Fix mix and relay deletion failure

- lib/cogctl/actions/bundles/create.ex
`display_error/1` chokes if given a list of items where at least one
item doesn't implement `String.Chars`. This scenario occurs when a
bundle config fails validation.
This commit adds logic to `lib/cogctl/actions/bundles/create.ex` which
converts validation errors of the form `{reason, field_path}` to the
string `"Invalid field '#{field_path}`: #{reason}".
> Ensure validation errors are converted to strings

- test/cogctl_test.exs
Update tests to expect cog-admin group and role. See-also: https://github.com/operable/cog/pull/529
> update tests for new bootstrap cog-admin group/role

- lib/cogctl/actions/relay_groups/assign.ex
- lib/cogctl/actions/relay_groups/unassign.ex
- lib/cogctl/actions/roles/grant.ex
- lib/cogctl/actions/roles/revoke.ex
- mix.exs
- mix.lock
- test/cogctl_test.exs
Changes to relay-groups to allow for multiple bundle assignments.
The syntax is now:
`cogctl relay-groups assign mygroup bundle1 bundle2 bundle3`
`cogctl relay-groups unassign mygroup bundle1 bundle2 bundle3`
depends on https://github.com/operable/cog-api-client/pull/89
resolves https://github.com/operable/cog/issues/536
> Support bulk un/assignments to relay-groups

- lib/cogctl/action_util.ex
- lib/cogctl/actions/relay_groups/create.ex
- lib/cogctl/actions/relay_groups/util.ex
- lib/cogctl/actions/relays/create.ex
- lib/cogctl/actions/relays/update.ex
- lib/cogctl/actions/relays/util.ex
- lib/cogctl/actions/users/util.ex
- mix.exs
- mix.lock
- test/cogctl_test.exs
* create relay and assign relay groups at the same time
* create relay groups and assign relays at the same time
This change does not create both using the same command and errors when trying to assign a group or a relay that does not exist to a newly created group or relay.
Fixes https://github.com/operable/cog/issues/535
> Simplify creation and assigning of relays to relay-groups

- lib/cogctl/action_util.ex
- lib/cogctl/actions/bundles/create.ex
- lib/cogctl/actions/bundles/delete.ex
- lib/cogctl/actions/chat_handles/create.ex
- lib/cogctl/actions/chat_handles/delete.ex
- lib/cogctl/actions/permissions.ex
- lib/cogctl/actions/relay_groups/add.ex
- lib/cogctl/actions/relay_groups/assign.ex
- lib/cogctl/actions/relay_groups/create.ex
- lib/cogctl/actions/relay_groups/remove.ex
- lib/cogctl/actions/relay_groups/unassign.ex
- lib/cogctl/actions/relays/create.ex
- lib/cogctl/actions/relays/update.ex
- lib/cogctl/actions/roles/rename.ex
- lib/cogctl/actions/triggers/create.ex
- lib/cogctl/actions/triggers/update.ex
- lib/cogctl/actions/users/create.ex
- lib/cogctl/actions/users/update.ex
- test/cogctl/action_util_test.exs
When the user fails to supply the proper args they are presented with a very unhelpful "Missing required arguments" message. This updates the `display_arguments_error` and `convert_to_params` to give a more informative message.
resolves https://github.com/operable/cog/issues/542
> Required args

- lib/cogctl/action_util.ex
- lib/cogctl/actions/relays/delete.ex
- test/cogctl_test.exs
cogctl displayed an error code after successfully deleting a relay. This should remove that.
resolves https://github.com/operable/cog/issues/541
> remove error code when deleting relays

- lib/cogctl/config.ex
This file will contain the password for the Cog admin user, so it should
be protected.
> Restrict permissions on generated ~/.cogctl file

- lib/cogctl/actions/relay_groups/util.ex
- lib/cogctl/actions/relays/util.ex
Currently the relay-group create (and relay create) return nil upon a successful creation and :error when something goes wrong. The function should return :ok when things are successful instead.
Connected to  https://github.com/operable/cog/issues/567
> Return :ok instead of nil when there are no errors

- lib/cogctl/actions/relays/create.ex
- lib/cogctl/actions/relays/util.ex
- test/cogctl_test.exs
This PR adds the enable flag to the options available for `relays create`. There was a need for a slight restructure since this would be done upon the successful creation of a relay.
Connected to https://github.com/operable/cog/issues/566
> Add an enable flag to the relay create action

- lib/cogctl/actions/bundles/create.ex
- lib/cogctl/actions/chat_handles/create.ex
- lib/cogctl/actions/groups/create.ex
- lib/cogctl/actions/permissions/create.ex
- lib/cogctl/actions/permissions/view.ex
- lib/cogctl/actions/roles/create.ex
- lib/cogctl/actions/rules/create.ex
- lib/cogctl/actions/triggers/create.ex
- lib/cogctl/actions/users/create.ex
- test/cogctl_test.exs
The lines that state "Created <resource>" lines have been removed. In a couple of cases (chat-handles and permissions), the relevant data has been added. All other just displayed the relevant data that was already being displayed.
For permissions, since the relevant information wasn't being displayed, the addition of a View is being used for rendering purposes.
Connected to https://github.com/operable/cog/issues/546
> Remove the 'Created' line and display relevant information

- lib/cogctl/actions/bootstrap.ex
- lib/cogctl/actions/bundles/create.ex
- mix.exs
- mix.lock
- test/support/cli_case.ex
When you bootstrap a system that is already bootstrapped you get a 423 back, which is technically an error. This would cause cogctl to exit with a status of 1. We want bootstrapping to be idempotent, so now if we get a 423, we just let the user know that the system is already bootstrapped and exit with a 0.
> Use the HTTP status code to determine success for bootstrapping

- lib/cogctl/actions/chat_handles.ex
- lib/cogctl/actions/chat_handles/create.ex
- lib/cogctl/actions/chat_handles/view.ex
- lib/cogctl/actions/permissions.ex
- lib/cogctl/actions/permissions/view.ex
This restructuring allows us to retrieve a permissions or chat-handle resource and render the output in a separate function. This way we can easily read and maintain how this information is displayed. It also allows for consistency in how the data is displayed.
Connected to https://github.com/operable/cog/issues/580
> Restructure the rendering of the Permissions and Chat-Handle resources

- lib/cogctl/optparse.ex
- test/cogctl/optparse_test.exs
Instead of crashing when a user passes an invalid arg, we should return an error to the user and exit gracefully.
resolves https://github.com/operable/cog/issues/634
> return a proper error to the user when an invalid option is passed

- lib/cogctl.ex
- lib/cogctl/action_util.ex
- test/cogctl_test.exs
`cogctl:` now prefixes error messages. This should make it easier to spot errors from cogctl when it's in the middle of a pipeline.
> add 'cogctl:' to error output

- lib/cogctl/optparse.ex
- test/cogctl/optparse_test.exs
Don't crash when a user passes a misspelled command. Instead give them a better suggestion.
resolves https://github.com/operable/cog/issues/685
> cogctl crash on bad commands

- lib/cogctl.ex
- lib/cogctl/actions/rules.ex
- lib/cogctl/config.ex
- lib/cogctl/optparse.ex
- test/cogctl/optparse_test.exs
* Adds an optional `--config-file` option. If present, this path takes precedence as configuration file location over all other settings.
* Allows a `$COGCTL_CONFIG_FILE` environment variable to be set. If present, this location will be used as the default configuration file path instead of `~/.cogctl`. As stated above, if the `--config-file` option always wins if it is also passed, whether or not the `$COGCTL_CONFIG_FILE` variable is set.
* In the absence of a `--config-file` option or a `$COGCTL_CONFIG_FILE` environment variable, continue to use `~/.cogctl` as the default configuration file.
This adds a `--config-file` option whose value will be used as the filename for all configuration file operations.
```
>> imbriaco @ trogdor [ ~/operable/cogctl (imbriaco/config-file-path *) ]
$ mv …
```
> allow config file location to be specified

- lib/cogctl/optparse.ex
Previously, the `:secure` option defaulted to `false`. This causes an unfortunate interaction with the way that profiles are loaded that means that we disregard the `secure:` field in config and always set it to false.
> default secure option to :undefined

- lib/cogctl.ex
- mix.exs
This application was not being started, which meant that its downstream dependencies were also not being started. This manifested as the `:ssl` application not running which prevented cogctl from talking to SSL based cog instances.
> start the :cog_api application 

- lib/cogctl/actions/profiles/create.ex
- lib/cogctl/optparse.ex
This will be primarily used by our docker-compose setup for Cog. Now that Cog can bootstrap itself we need to automatically generate a `~/.cogctl` file upon setup, when previously we could just call `cogctl bootstrap`, which would create the default profile for us. Now instead we can just call `cogctl profiles create default --rest-user $COG_BOOTSTRAP_USER --rest-password $COG_BOOTSTRAP_PASSWORD ...`
> Add profiles create action

- lib/cogctl/action_util.ex
- lib/cogctl/actions/bundle/install.ex
- lib/cogctl/actions/chat_handles/create.ex
- lib/cogctl/actions/chat_handles/delete.ex
- lib/cogctl/actions/permissions.ex
- lib/cogctl/actions/relay_groups/add.ex
- lib/cogctl/actions/relay_groups/assign.ex
- lib/cogctl/actions/relay_groups/create.ex
- lib/cogctl/actions/relay_groups/remove.ex
- lib/cogctl/actions/relay_groups/unassign.ex
- lib/cogctl/actions/relays/create.ex
- lib/cogctl/actions/relays/update.ex
- lib/cogctl/actions/roles/info.ex
- lib/cogctl/actions/roles/rename.ex
- lib/cogctl/actions/triggers/create.ex
- lib/cogctl/actions/triggers/update.ex
- lib/cogctl/actions/users/create.ex
- lib/cogctl/actions/users/info.ex
- lib/cogctl/actions/users/update.ex
We're now only sending params we expect down to the cog-api-client. Things like `config_path` are no longer sent in API requests.
> Whitelist params

- .buildkite/hooks/pre-command
When we kick off a dependent cogctl build from a cog build, we'll want
to run against the version of cog that just built. In those cases, a
`COG_BRANCH` environment variable will be present which we can use.
Also, TIL: apparently Buildkite runs scripts with `set -u`
See operable/cog#1047
Fixes operable/cog#1035
UPDATE:
If a build is triggered from cog, the cogctl tests will run using whatever branch of cog just built. If the build is triggered from cogctl, we'll try to use a branch in cog that has the same name as what's building in cogctl. If no such branch exists, we'll build from the master branch of cog.
> Parameterize the cog server being built

- lib/cogctl/actions/bundle/install.ex
- test/cogctl/bundles_test.exs
- test/fixtures/cassettes/installing_with_stdin.json
- test/support/bundle_helpers.ex
Resolves https://github.com/operable/cog/issues/1065
I'm thinking that the stdin bits could use a test, but I'm at a loss as to how to do it. Any input appreciated, but regardless this should at least fix the bug.
> Use the spanner return values to determine the type of bundle install

- .buildkite/pipeline.yml
- .buildkite/scripts/select_pipeline.sh
- .buildkite/scripts/triggered_integration.sh
- .buildkite/standard_pipeline.yml
- .buildkite/triggered_pipeline.yml
- .dockerignore
- .gitignore
- docker-compose.cog.yml
Cog builds now trigger a cogctl pipeline at the end. We now retrieve
the code from the branch of Cog that just built and substitute it for
the `cog-preview` image we would otherwise use.
We can't use Buildkite's built-in Docker Compose support because it
doesn't appear to support layering of compose files, which is what we
need here. As a result, we roll our own support, but using pretty much
the exact same approach that Buildkite takes.
We only bother running the integration tests, because that's what hits
the actual server.
Ideally, we'd also want the "normal" cogctl runs (i.e., not triggered by
cog) to pull from a matching branch (or master), but we can let that
wait until we get the real Dockerfile in cog refactored a bit; right now
the builds for that image can be a bit long, and we …
> Properly run cog-triggered pipelines

- mix.lock
We just updated the yaml_elixir dependency, and wanted to make sure
this was up-to-date as well.
> Update spanner dependency

- mix.lock
- test/cogctl_test.exs
Removes v3 bundle support; adds v5
Updates the tests to use a v5 testing bundle, too.
> Bump Spanner

- test/cogctl_test.exs
Triggers must refer to an existing user
> Update tests for trigger user behavior

- mix.exs
- mix.lock
More details in `configparser_ex` PR: https://github.com/easco/configparser_ex/pull/3
Fixes https://github.com/operable/cog/issues/1279
> Bump configparser_ex to version with comment prefix regex fix

- test/cogctl_test.exs
Our tests were silently failing to delete records that still had associations restricted by our new foreign key constraints. This PR fixes those issues for a green test suite.
> Fix fkey restrictions

- .buildkite/scripts/build.sh
- .dockerignore
- .gitignore
- Dockerfile.alpine
- Dockerfile.ubuntu
- Makefile
- cogctl/__init__.py
- cogctl/cli/version.py
- features/version.feature
- scripts/write-git-info
- scripts/write-git-sha
This PR tweaks the cogctl build in two significant ways:
1. `cogctl version` now returns git tag information in additional to commit SHA. The current branch name will be used when building from a untagged commit.
1. Building a Docker image from `Dockerfile.alpine` and `Dockerfile.ubuntu` will also build `/src/dist/cogctl` inside that image. The executable is also copied to `/usr/bin`. This is done to simplify injecting `cogctl` into Cog release builds.
> Tweak cogctl build process

- .buildkite/pipeline.yml
- .buildkite/scripts/build.sh
- .buildkite/scripts/push_image.sh
To make our current Cog builds easier, we're going to start pulling the
binaries out of the containers we build them in here in CI. (We're
opting for that right now as opposed to setting up some kind of artifact
repository. This is for expediency and incremental improvement; we'll
get an artifact repository soon.)
When we build on the "master" branch, we'll take the built image (which
we now push to our `cogctl-testing` repository, since there's no
guarantee we'll be running on the same agent that built the image in the
first place) and push it to our `cogctl` repository, tagged with both the platform and "master".
This tag will "float" with whatever the current master branch generates;
it will be replaced the next time the build runs. A `git_commit` Docker
label is added to the image, …
> Promote master-built images to the cogctl repo

- scripts/write-git-info
Previously, we relied on the output of `git describe --tags`, which
appends information on how many commits away from the last tag the
current commit is. We subsequently processed this to try and determine
if the output referred directly to a tag. Unfortunately, this would
erroneously filter out tags that contained hyphens.
Now, we add `--exact-match` to the invocation, which will return the
name of the tag the current commit lies on, if indeed it does.
Note that this falls apart if more than one tag point to the current
commit, but with how we tag, that's not likely to occur.
> Add --exact-match to tag detection
